---
- name: Nerd Fonts Management
  block:
    - name: Check if font management script exists
      stat:
        path: "{{ playbook_dir }}/../manage_fonts.sh"
      register: font_script
      delegate_to: localhost

    - name: Fail if font script not found
      fail:
        msg: "Font management script not found at {{ playbook_dir }}/../manage_fonts.sh"
      when: not font_script.stat.exists

    - name: Make font management script executable
      file:
        path: "{{ playbook_dir }}/../manage_fonts.sh"
        mode: '0755'
      delegate_to: localhost

    - name: Install selected fonts via script
      shell: |
        cd {{ playbook_dir }}/..
        ./manage_fonts.sh --ansible install {{ nerd_fonts_to_install | join(' ') }}
      register: font_install_result
      when: 
        - nerd_fonts_to_install is defined
        - nerd_fonts_to_install | length > 0
      changed_when: "'✓' in font_install_result.stdout"

    - name: Install all fonts if none specified
      shell: |
        cd {{ playbook_dir }}/..
        ./manage_fonts.sh --ansible install all
      register: font_install_all_result
      when: 
        - nerd_fonts_to_install is not defined or nerd_fonts_to_install | length == 0
        - install_all_fonts | default(false) | bool
      changed_when: "'✓' in font_install_all_result.stdout"

    - name: Get font installation status
      shell: |
        cd {{ playbook_dir }}/..
        ./manage_fonts.sh --ansible status
      register: font_status
      changed_when: false

    - name: Display font installation results
      debug:
        msg: "{{ font_status.stdout_lines }}"
      when: font_status is defined

  rescue:
    - name: Handle font installation errors
      debug:
        msg: "Font installation failed: {{ ansible_failed_result.msg }}"

  tags:
    - fonts
    - nerd-fonts