---
- name: Configure User Shell Environment
  hosts: localhost
  become: yes
  vars:
    # Variables will ideally be defined in group_vars/all.yml or shell.yml
    preferred_shell: "/bin/bash" # Default
    bash_prompt_preference: "starship" # 'none' or 'starship'
    zsh_prompt_preference: "none"   # 'none', 'starship', or 'p10k'
    config_dir: "{{ user_home }}/.config"
    local_bin_dir: "{{ user_home }}/.local/bin"
    omz_path: "{{ user_home }}/.oh-my-zsh"
    p10k_theme_path_omz: "{{ omz_path }}/custom/themes/powerlevel10k"
    p10k_config_path: "{{ user_home }}/.p10k.zsh"
    starship_config_path: "{{ config_dir }}/starship.toml"
    user_home: "{{ ansible_user_dir }}"
    install_nerd_fonts: true # Flag to control Nerd Fonts installation

  tasks:
    - name: Ensure base directory structure exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ config_dir }}"
        - "{{ local_bin_dir }}"
      when: ansible_os_family in ['Linux', 'Darwin'] # Target Linux and macOS

    - name: Install Zsh package if preferred
      ansible.builtin.package:
        name: zsh
        state: present
      become: true
      when: preferred_shell is search('zsh') and ansible_os_family in ['Linux', 'Darwin']

    - name: Set user's default shell if preferred
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: "{{ preferred_shell }}"
      become: true
      when: preferred_shell is defined and preferred_shell != "" and ansible_os_family in ['Linux', 'Darwin']

    # --- Nerd Fonts Installation ---
    - name: Install Nerd Fonts (Debian/Ubuntu)
      ansible.builtin.package:
        name: fonts-firacode-nerd
        state: present
      become: true
      when: ansible_os_family == 'Debian' and install_nerd_fonts

    - name: Install Nerd Fonts (Arch Linux)
      ansible.builtin.package:
        name: nerd-fonts-fira-code
        state: present
      become: true
      when: ansible_os_family == 'Archlinux' and install_nerd_fonts

    - name: Install Nerd Fonts (macOS via Homebrew)
      community.general.homebrew_tap:
        name: homebrew/cask-fonts
      when: ansible_os_family == 'Darwin' and install_nerd_fonts

    - name: Install Nerd Fonts (macOS via Homebrew - FiraCode Nerd Font)
      community.general.homebrew_cask:
        name: font-fira-code-nerd-font
        state: present
      when: ansible_os_family == 'Darwin' and install_nerd_fonts

    # --- Starship Installation and Configuration ---
    - name: Install Starship binary if selected for Bash or Zsh
      ansible.builtin.shell: |
        curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir {{ local_bin_dir }}
      args:
        creates: "{{ local_bin_dir }}/starship"
      when: (bash_prompt_preference == 'starship' or zsh_prompt_preference == 'starship') and ansible_os_family in ['Linux', 'Darwin']

    - name: Template Starship config (Tokyo Night preset)
      ansible.builtin.template:
        src: starship.toml.j2
        dest: "{{ starship_config_path }}"
        mode: '0644'
        backup: yes
      when: (bash_prompt_preference == 'starship' or zsh_prompt_preference == 'starship') and ansible_os_family in ['Linux', 'Darwin']

    # --- Oh My Zsh Installation and Powerlevel10k ---
    - name: Install Oh My Zsh if P10k is preferred for Zsh
      ansible.builtin.shell: |
        export ZSH="{{ omz_path }}" && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: "{{ omz_path }}/oh-my-zsh.sh"
      environment:
        ZSH: "{{ omz_path }}"
      when: preferred_shell is search('zsh') and zsh_prompt_preference == 'p10k' and ansible_os_family in ['Linux', 'Darwin']

    - name: Install Powerlevel10k theme for OMZ if preferred
      ansible.builtin.git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "{{ p10k_theme_path_omz }}"
        depth: 1
        version: v1.20.0
      when: preferred_shell is search('zsh') and zsh_prompt_preference == 'p10k' and ansible_os_family in ['Linux', 'Darwin']

    - name: Template default P10k config file if preferred
      ansible.builtin.template:
        src: p10k.zsh.j2
        dest: "{{ p10k_config_path }}"
        mode: '0644'
        backup: yes
      when: preferred_shell is search('zsh') and zsh_prompt_preference == 'p10k' and ansible_os_family in ['Linux', 'Darwin']

    # --- Template Shell Configuration Files ---
    - name: Template .bashrc file
      ansible.builtin.template:
        src: bashrc.j2 # Single template
        dest: "{{ user_home }}/.bashrc"
        mode: '0644'
        backup: yes
      when: ansible_os_family in ['Linux', 'Darwin']

    - name: Template .zshrc file
      ansible.builtin.template:
        src: zshrc.j2 # Single template
        dest: "{{ user_home }}/.zshrc"
        mode: '0644'
        backup: yes
      when: preferred_shell is search('zsh') and ansible_os_family in ['Linux', 'Darwin']