---
- name: Install Azure CLI
  apt:
    deb: https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.56.0-1~focal_all.deb
    state: present

- name: Install AWS CLI
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
