---
- name: Ensure basic utilities are installed
  become: yes
  ansible.builtin.package:
    name:
      - git
      - curl
      - wget
    state: present

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'

- name: Ensure .local/bin directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.local/bin"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'

- name: Set Git user name (optional)
  ansible.builtin.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name | default('') }}"
  when: git_user_name is defined

- name: Set Git user email (optional)
  ansible.builtin.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email | default('') }}"
  when: git_user_email is defined