---
# Default Variables for my-awesome-shell-setup
# These can be overridden by the install_custom_shell.sh script
# or by passing --extra-vars="key=value" to ansible-playbook.

# --- Shell & Prompt Selection ---
# Set these or pass via --extra-vars for testing
preferred_shell: "/usr/bin/zsh"  # Options: "/usr/bin/zsh" or "/bin/bash"
prompt_framework: "starship"     # Options: "starship" or "p10k"

# --- Backup Configuration ---
backup_existing_configs: true
backup_dir: "{{ user_home }}/.config_backups/{{ ansible_date_time.iso8601_basic_short }}"

# --- Starship Configuration ---
starship_template: "tokyo-night"  # Must match filename in starship_templates/ (without .toml)
                                   # Available: bracketed-segments, catppuccin-powerline, jetpack,
                                   #            nerd-font-symbols, no-empty-icons, no-nerd-font,
                                   #            no-runtime-versions, pastel-powerline, plain-text-symbols,
                                   #            pure-preset, tokyo-night

# --- Powerlevel10k Configuration ---
p10k_template: "p10k-rainbow"  # Must match filename in p10k_templates/ (without .zsh)
                                # Available: p10k-classic, p10k-lean-8colors, p10k-lean,
                                #            p10k-pure, p10k-rainbow, p10k-robbyrussell

# --- Zsh Plugins Configuration ---
# For Starship standalone setup (without Oh My Zsh)
zsh_plugins_dir: "{{ user_home }}/.zsh"
zsh_autosuggestions_repo: "https://github.com/zsh-users/zsh-autosuggestions"
zsh_syntax_highlighting_repo: "https://github.com/zsh-users/zsh-syntax-highlighting"

# --- Oh My Zsh Configuration ---
# Oh My Zsh path (used when P10k is selected)
omz_path: "{{ user_home }}/.oh-my-zsh"
omz_custom_path: "{{ omz_path }}/custom"
omz_themes_path: "{{ omz_custom_path }}/themes"
omz_plugins_path: "{{ omz_custom_path }}/plugins"
p10k_theme_path_omz: "{{ omz_themes_path }}/powerlevel10k"

# --- Default Tool Installation ---
# Core Tools
install_zsh: true  # Install Zsh if not present and preferred_shell is zsh

# --- DevOps Essentials ---
# Containerization
install_docker: true
install_kubectl: true
install_helm: false
install_docker_compose: true

# Infrastructure as Code
install_terraform: true
install_awscli: false
install_gcloud: false
install_azurecli: false

# --- Full Stack & AI/ML Essentials ---
# Python
install_python: true
python_versions:
  - "3.8"
  - "3.11"

# Python linters and formatters
install_flake8: true
install_black: true
install_isort: true

# Node.js
install_nvm: true

# Package Managers
install_pip: true
install_npm: true
install_uv: true
install_poetry: true

# --- Common Utilities ---
install_git: true
install_curl: true
install_wget: true
install_jq: true
install_tmux: true
install_ripgrep: true # Faster grep

# --- Nerd Fonts Configuration ---
nerd_fonts_to_install:
  - CascadiaCode
  - FiraCode
  - JetBrainsMono
  # - Hack
  # - SourceCodePro
  # - UbuntuMono

# Set to true to install all available fonts
install_all_fonts: false

# Font management options
font_backup_enabled: true
font_cache_refresh: true

# --- Configuration Paths ---
# Assumes user running ansible is the target user
user_home: "{{ ansible_user_dir }}"
config_dir: "{{ user_home }}/.config"
local_bin_dir: "{{ user_home }}/.local/bin"

# Starship configuration file path
starship_config_path: "{{ config_dir }}/starship.toml"

# P10k configuration file path
p10k_config_path: "{{ user_home }}/.p10k.zsh"

# --- Git User Info (Optional - Used by common role) ---
# git_user_name: "Your Name"
# git_user_email: "your.email@example.com"