---
# Default Variables for my-awesome-shell-setup
# These can be overridden by the install_custom_shell.sh script
# or by passing --extra-vars="key=value" to ansible-playbook.

# --- Shell & Prompt Selection (Set by script) ---
preferred_shell: ""
prompt_framework: ""

# --- Default Tool Installation ---
# These tools will be installed by default.
# Optional/additional tools will be managed by a separate script.

# --- Core Tools ---
install_zsh: false # Install Zsh if not present (set by script)

# --- DevOps Essentials ---
# Containerization
install_docker: true
install_kubectl: true
install_helm: true
install_docker_compose: true

# Infrastructure as Code
install_terraform: true
install_awscli: false
install_gcloud: false
install_azurecli: false

# --- Full Stack & AI/ML Essentials ---
# Python
install_python: true
python_versions:
  - "3.8"
  - "3.11"

# Node.js
install_nvm: true

# Package Managers
install_pip: true
install_npm: true

# --- Common Utilities ---
install_git: true
install_curl: true
install_wget: true
install_jq: true
install_tmux: true
install_vim: true # Keep vim as a base editor
install_ripgrep: true # Faster grep

# Nerd Fonts Configuration
nerd_fonts_to_install:
  - CascadiaCode
  - FiraCode
  - JetBrainsMono
  # - Hack
  # - SourceCodePro
  # - UbuntuMono

# Set to true to install all available fonts
install_all_fonts: false

# Font management options
font_backup_enabled: true
font_cache_refresh: true

# --- Configuration Paths ---
# Assumes user running ansible is the target user
user_home: "{{ ansible_user_dir }}"
config_dir: "{{ user_home }}/.config"
local_bin_dir: "{{ user_home }}/.local/bin"

# Starship configuration file path (will be created if Starship is chosen later)
starship_config_path: "{{ config_dir }}/starship.toml"

# P10k configuration file path (will be created if P10k is chosen later)
p10k_config_path: "{{ user_home }}/.p10k.zsh"

# Oh My Zsh path (will be installed if Zsh and P10k are chosen later)
omz_path: "{{ user_home }}/.oh-my-zsh"
omz_custom_path: "{{ omz_path }}/custom"
omz_themes_path: "{{ omz_custom_path }}/themes"
p10k_theme_path_omz: "{{ omz_themes_path }}/powerlevel10k"

# --- Git User Info (Optional - Used by common role maybe) ---
# git_user_name: "Your Name"
# git_user_email: "your.email@example.com"