---
- name: Install Python and pip (system level)
  become: true
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
  register: devtools_python_system_install_result
  failed_when: devtools_python_system_install_result.failed | default(false)

- name: Install uv
  become: true
  ansible.builtin.pip:
    name: uv
    executable: pip3
    state: present
  register: devtools_uv_install_result
  failed_when: devtools_uv_install_result.failed | default(false)

- name: Install ruff via uv
  become: true
  ansible.builtin.command:
    cmd: uv tool install ruff
  register: devtools_ruff_install_result
  failed_when: devtools_ruff_install_result.rc != 0
  changed_when: devtools_ruff_install_result.rc == 0
  when:
    - devtools_uv_install_result is succeeded
    - devtools_python_system_install_result is succeeded
