---
- name: Ensure VS Code config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/Code/User"
    state: directory
    mode: '0755'

- name: Apply VS Code settings
  copy:
    src: files/settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    mode: '0644'

- name: Install VS Code
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    state: present

- name: Apply VS Code settings
  copy:
    src: files/settings.json
    dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
    mode: '0644'
  become: no  # Avoid running as root

- name: Import VS Code profile
  copy:
    src: files/Shanmeistro.code-profile
    dest: ~/.config/Code/User/profiles/Shanmeistro.code-profile

- name: Install VS Code Extensions
  shell: |
    xargs -n 1 code --install-extension < files/vscode-extensions.txt
