---
- name: Setup local dev environment
  hosts: localhost
  connection: local
  become: true # Generally needed for most tasks
  vars:
    user_home: "{{ ansible_user_dir }}"
    config_dir: "{{ user_home }}/.config"
    local_bin_dir: "{{ user_home }}/.local/bin"

    # Starship configuration file path
    starship_config_path: "{{ config_dir }}/starship.toml"

    # P10k configuration file path
    p10k_config_path: "{{ user_home }}/.p10k.zsh"

    # Oh My Zsh path
    omz_path: "{{ user_home }}/.oh-my-zsh"
    omz_custom_path: "{{ omz_path }}/custom"
    omz_themes_path: "{{ omz_custom_path }}/themes"
    p10k_theme_path_omz: "{{ omz_themes_path }}/powerlevel10k"

  tasks:
    - name: Include common role (basic setup)
      ansible.builtin.include_role:
        name: common
      tags:
        - common

    - name: Include shell role (shell and prompt config)
      ansible.builtin.include_role:
        name: shell
      tags:
        - shell

    - name: Include fonts role (nerd fonts installation)
      ansible.builtin.include_role:
        name: fonts
      tags:
        - fonts

    - name: Include sysadmin-tools role
      ansible.builtin.include_role:
        name: sysadmin-tools
      tags:
        - sysadmin-tools

    - name: Include devtools role (development tools)
      ansible.builtin.include_role:
        name: devtools
      tags:
        - devtools
