---
- name: Configure Dev Environment
  hosts: localhost
  become: yes
  vars:
    update_zsh_from_repo: false
    update_configs: false
    update_vscode: false
    update_cloud_cli: false
    update_devtools: false
    update_python: false
    update_nerd_fonts: false

- name: Check if running inside WSL2
  command: uname -r
  register: uname_output
  changed_when: false

- name: Set is_wsl2 fact
  set_fact:
    is_wsl2: "{{ 'microsoft-standard' in uname_output.stdout }}"

  roles:
    - role: zsh
      vars:
        update_configs: "{{ update_configs }}"
      when: update_zsh_from_repo

    - role: vscode
      vars:
        update_configs: "{{ update_vscode }}"

    - role: cloud-cli
      vars:
        update_configs: "{{ update_cloud_cli }}"

    - role: devtools
      vars:
        update_configs: "{{ update_devtools }}"

    - role: python
      vars:
        update_configs: "{{ update_python }}"

    - role: nerd-fonts
      vars:
        update_configs: "{{ update_nerd_fonts }}"

# - name: Run for specific OS
#   debug:
#     msg: "Running on {{ ansible_distribution }}"
#   when: ansible_distribution == "Ubuntu"
