---
- name: Configure Dev Environment
  hosts: localhost
  become: yes
  vars:
    update_zsh_from_repo: false
    update_configs: false

  roles:
    - role: zsh
      vars:
        update_configs: "{{ update_configs }}"
      when: update_zsh_fromrepo
    - role: vscode
    - role: cloud-cli
    - role: devtools
    - role: python
    - role: nerd-fonts

# - name: Run for specific OS
#   debug:
#     msg: "Running on {{ ansible_distribution }}"
#   when: ansible_distribution == "Ubuntu"
